### ISSUE TITLE
HighLight.js does not detect indentation & formats the code

### ISSUE THREAD

**Issue by richkdev** [CSP02/CSPSH#21]
Hey there,

It seems as if no line of code detects indentations and formats the code. Check [SyntaxHighLight.js](https://github.com/Chandra-sekhar-pilla/CSPSH/blob/main/Source/CSPSH/SyntaxHighLight.js) to fix this issue.

Thanks,
_Richmond Kleinson_

**Comment by Chandra-sekhar-pilla** [comment]
Hey Richmond Kleinson, 

Thanks for noticing and it was fixed in v5.0.0 pre-release. 
I filtered  all the tab spaces from the tokens.

Thanks again 😊
